"""Validation: Tier 2 benches (SITF, NETD, 3-D noise, MTF) and the NumPy-only metric functions.

Also the Tier 4 reading layer that decides what a statistic measured on somebody else's clip is
allowed to claim: :mod:`~irsim.validation.flat` chooses the windows (no horizon, no cloud, no
target) and :mod:`~irsim.validation.codec` measures the floor the 8-bit, lossily-coded storage
path puts under every one of them.

docs/physics-model.md §15
"""

from irsim.validation.aerial import (
    AerialTarget,
    apparent_target_radiance,
    background_radiance,
    target_contrast,
    target_leaving_radiance,
    zero_contrast_elevation,
)
from irsim.validation.aerial_scene import (
    AerialScene,
    SceneTarget,
    build_aerial_gbuffer,
    elevation_grid_rad,
)
from irsim.validation.bench import SitfResult, measured_netd_k, sitf
from irsim.validation.codec import (
    Blockiness,
    CodecFloor,
    FlaggedDecomposition,
    blockiness,
    codec_floor,
    flag_codec_limited,
    quantisation_floor,
    quantiser_step,
    sheppard_correct,
)
from irsim.validation.display_signature import (
    AgcSignature,
    AgcVerdict,
    EdgeOvershoot,
    RecorderConversion,
    ReplacedPixels,
    agc_signature,
    edge_overshoot,
    replaced_pixel_map,
    require_display_output,
)
from irsim.validation.flat import (
    FlatRegion,
    TemporalNoise,
    find_flat_regions,
    representative_frame,
    robust_noise_scale,
    temporal_noise,
    temporal_std_map,
)
from irsim.validation.measured import (
    MEASURED_QUANTITIES,
    Comparison,
    compare_absolute,
    compare_shape,
    load_measured_pairs,
    measured_path,
)
from irsim.validation.mtf import SlantEdgeResult, slant_edge_mtf
from irsim.validation.noise import (
    Decomposition3D,
    SpatialPSD,
    TemporalShape,
    compare_psd,
    decompose_3d,
    estimate_floors,
    spatial_psd,
    temporal_psd,
    temporal_shape,
)
from irsim.validation.shutter import (
    MIN_INTERVAL_CLIP_S,
    Freeze,
    LineMeans,
    PatternGrowth,
    find_freezes,
    fit_pattern_growth,
    freeze_intervals_s,
    line_means,
    pattern_energy,
)
from irsim.validation.signal_path import (
    ANALYSERS,
    SIGNAL_PATHS,
    AnalyserRequirement,
    SignalPath,
    allows,
    permitted_analysers,
    require_signal_path,
)

__all__ = [
    "MEASURED_QUANTITIES",
    "Comparison",
    "compare_absolute",
    "compare_shape",
    "load_measured_pairs",
    "measured_path",
    "AerialScene",
    "AerialTarget",
    "SceneTarget",
    "build_aerial_gbuffer",
    "elevation_grid_rad",
    "apparent_target_radiance",
    "background_radiance",
    "target_contrast",
    "target_leaving_radiance",
    "zero_contrast_elevation",
    "SitfResult",
    "SlantEdgeResult",
    "slant_edge_mtf",
    "measured_netd_k",
    "sitf",
    "Decomposition3D",
    "SpatialPSD",
    "TemporalShape",
    "compare_psd",
    "decompose_3d",
    "estimate_floors",
    "spatial_psd",
    "temporal_psd",
    "temporal_shape",
    "Blockiness",
    "CodecFloor",
    "FlaggedDecomposition",
    "FlatRegion",
    "TemporalNoise",
    "blockiness",
    "codec_floor",
    "find_flat_regions",
    "flag_codec_limited",
    "quantisation_floor",
    "quantiser_step",
    "representative_frame",
    "robust_noise_scale",
    "sheppard_correct",
    "temporal_noise",
    "temporal_std_map",
    "MIN_INTERVAL_CLIP_S",
    "Freeze",
    "LineMeans",
    "PatternGrowth",
    "find_freezes",
    "fit_pattern_growth",
    "freeze_intervals_s",
    "line_means",
    "pattern_energy",
    "AgcSignature",
    "AgcVerdict",
    "EdgeOvershoot",
    "RecorderConversion",
    "ReplacedPixels",
    "agc_signature",
    "edge_overshoot",
    "replaced_pixel_map",
    "require_display_output",
    "ANALYSERS",
    "SIGNAL_PATHS",
    "AnalyserRequirement",
    "SignalPath",
    "allows",
    "permitted_analysers",
    "require_signal_path",
]
