#!/usr/bin/env python3
"""Build the project site — everything this repository knows, as one browsable thing.

    python scripts/build_site.py                 # build into _site/
    python scripts/build_site.py --serve         # build, then serve it on http://localhost:8000
    python scripts/build_site.py --no-media      # skip the gallery encode (documents only, fast)
    python scripts/build_site.py --out DIR       # somewhere else
    python scripts/build_site.py --outputs DIR   # a different render tree ($IRSIM_OUTPUTS)

The site is static, has no build dependency outside this repository, and is published by pushing
`_site/` to the `gh-pages` branch (`make site-publish`). It is built from three kinds of source:

1. **The documents that already exist** — `docs/physics-model.md`, the roadmap, every ADR, the
   validation reports, the changelog, README and CLAUDE.md. Rendered, not duplicated: the site
   cannot drift from them because it has no copy of them.
2. **The repository itself** — the module map, the configuration catalogue and the numbers on the
   front page are measured at build time (`scripts/site_survey.py`).
3. **The renders** — `site/gallery.yaml` names the frames and clips worth showing and
   `scripts/site_gallery.py` re-encodes them for the web. `outputs/` is 8 GB and gitignored, so
   the site carries a web-sized subset and says so.

Output is a plain directory of HTML with relative links throughout, which works both at
`file://`/localhost and under the `/<repo>/` prefix GitHub project pages are served from.
"""

from __future__ import annotations

import argparse
import datetime as dt
import html
import json
import os
import pathlib
import posixpath
import re
import shutil
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import site_gallery  # noqa: E402
import site_markdown  # noqa: E402
import site_survey  # noqa: E402
from site_layout import GITHUB, NavGroup, NavItem, Page, relative, render_page  # noqa: E402

REPO = pathlib.Path(__file__).resolve().parents[1]

#: The documents rendered as their own page: source, url, title, and the nav group it belongs to.
DOCUMENTS: list[tuple[str, str, str, str, str]] = [
    (
        "docs/physics-model.md",
        "physics/",
        "Physics model",
        "Physics",
        "The specification every equation in the code cites. It is the source of truth, "
        "not a summary.",
    ),
    (
        "docs/spec-issues.md",
        "spec-issues/",
        "Spec issues",
        "Physics",
        "Contradictions found in the specification, and the resolution the code assumes.",
    ),
    (
        "docs/roadmap.md",
        "roadmap/",
        "Roadmap",
        "Plan",
        "Milestones, one-commit steps, risks and the ADR backlog. The queue at the top is "
        "generated.",
    ),
    (
        "CHANGELOG.md",
        "changelog/",
        "Changelog",
        "Plan",
        "Every step that shipped, with the measurement that justified it.",
    ),
    (
        "README.md",
        "status/",
        "Status",
        "Start",
        "The subsystem status table: what is implemented, what it is verified against, and "
        "what is not.",
    ),
    (
        "CLAUDE.md",
        "guide/",
        "Working agreement",
        "Reference",
        "The non-negotiables, the repository layout and what counts as a finished step.",
    ),
]

#: Where each directory of documents lands, and how its index describes it.
COLLECTIONS: list[tuple[str, str, str, str, str]] = [
    (
        "docs/decisions",
        "decisions/",
        "Decision log",
        "Plan",
        "Every choice with consequences that outlive its commit — including the approximations "
        "taken "
        "on purpose, which is what a reader six months later cannot reconstruct.",
    ),
    (
        "docs/validation",
        "validation/",
        "Validation",
        "Evidence",
        "What has been measured, against what, and where it fails. A report here is generated by a "
        "script in `scripts/`, never written by hand.",
    ),
    (
        "docs/research",
        "research/",
        "Research",
        "Evidence",
        "The surveys the plan is derived from: production IR simulators, published datasheets, "
        "measurement standards and the sim-to-real literature.",
    ),
]

NAV_ORDER = ["Start", "Demos", "Physics", "Plan", "Evidence", "Reference"]


# ---------------------------------------------------------------------------------------------
# link resolution


class Resolver:
    """Rewrites a document's own links so they point at the built site.

    A link that names another rendered document becomes a relative site link; one that names a file
    in the repository (a module, a config, a script) becomes a link to it on GitHub, so following
    a citation from the physics model lands on the code that implements it. Anything else is left
    exactly as written.
    """

    def __init__(self, pages: dict[str, str], repo: pathlib.Path) -> None:
        self.pages = pages
        self.repo = repo
        #: Links naming a document that is neither a page nor a file in the tree. These are dead
        #: references in the source documents, so the build reports them instead of quietly
        #: publishing a 404 -- a renamed ADR is the usual cause.
        self.unresolved: set[tuple[str, str]] = set()

    def for_page(self, source: str | None, url: str):  # -> Callable[[str], str]
        base = posixpath.dirname(source) if source else ""

        def resolve(href: str) -> str:
            if not href or href.startswith(("http://", "https://", "mailto:", "#")):
                return href
            path, _, fragment = href.partition("#")
            fragment = f"#{fragment}" if fragment else ""
            target = posixpath.normpath(posixpath.join(base, path)) if path else source or ""
            if target in self.pages:
                return relative(url, self.pages[target]) + fragment
            if (self.repo / target).exists():
                return f"{GITHUB}/blob/main/{target}{fragment}"
            if path.endswith(".md"):
                self.unresolved.add((source or url, href))
            return href

        return resolve


# ---------------------------------------------------------------------------------------------
# pages built from documents


def document_page(
    repo: pathlib.Path,
    source: str,
    url: str,
    title: str,
    group: str,
    subtitle: str,
    resolver: Resolver,
) -> Page:
    text = (repo / source).read_text(encoding="utf-8")
    text = _strip_leading_title(text)
    doc = site_markdown.render(text, resolver.for_page(source, url))
    return Page(
        url=url,
        title=title,
        subtitle=subtitle,
        body=doc.html,
        nav_section=group,
        headings=doc.headings,
        source=source,
        search_text=_plain(doc.html),
    )


def _strip_leading_title(text: str) -> str:
    """Drop a document's own `# Title` — the page head already shows one."""
    lines = text.split("\n")
    for index, line in enumerate(lines):
        if line.startswith("# "):
            return "\n".join(lines[:index] + lines[index + 1 :])
        if line.strip():
            break
    return text


def _plain(markup: str) -> str:
    """Tags out, entities out: what the search index stores."""
    text = re.sub(r"<(script|style)[^>]*>.*?</\1>", " ", markup, flags=re.S)
    text = re.sub(r"<[^>]+>", " ", text)
    return re.sub(r"\s+", " ", html.unescape(text)).strip()


def decision_index(adrs: list[site_survey.Adr], url: str, group: str, blurb: str) -> Page:
    rows = []
    for adr in sorted(adrs, key=lambda a: a.number):
        status = adr.status.split()[0].rstrip(".,")
        rows.append(
            f'<tr data-status="{html.escape(status.lower())}">'
            f'<td class="nowrap">{adr.number}</td>'
            f'<td><a href="{relative(url, adr.url)}">{html.escape(adr.title)}</a></td>'
            f"<td>{html.escape(adr.status)}</td>"
            f'<td class="nowrap">{html.escape(adr.date)}</td></tr>'
        )
    body = [
        f"<p>{site_markdown.render(blurb).html[3:-4]}</p>",
        '<p class="filterline"><input id="adr-filter" type="search" placeholder="Filter '
        f'{len(adrs)} decisions…" aria-label="Filter decisions"></p>',
        "<div class='table-wrap'><table id=\"adr-table\"><thead><tr><th>#</th><th>decision</th>"
        "<th>status</th><th>date</th></tr></thead><tbody>",
        *rows,
        "</tbody></table></div>",
    ]
    return Page(
        url=url,
        title="Decision log",
        subtitle=f"{len(adrs)} architecture decision records.",
        body="\n".join(body),
        nav_section=group,
        wide=True,
        search_text=" ".join(a.title for a in adrs),
    )


def collection_index(pages: list[Page], url: str, title: str, group: str, blurb: str) -> Page:
    cards = []
    for page in sorted(pages, key=lambda p: p.title):
        summary = html.escape(page.search_text[:220])
        cards.append(
            f'<a class="card" href="{relative(url, page.url)}"><h3>{html.escape(page.title)}</h3>'
            f"<p>{summary}…</p></a>"
        )
    body = [
        f"<p>{site_markdown.render(blurb).html[3:-4]}</p>",
        '<div class="cards">',
        *cards,
        "</div>",
    ]
    return Page(
        url=url,
        title=title,
        subtitle=f"{len(pages)} document(s).",
        body="\n".join(body),
        nav_section=group,
        wide=True,
    )


# ---------------------------------------------------------------------------------------------
# the front page


def home_page(
    repo: pathlib.Path, stats: dict[str, int], plan: site_survey.Plan | None, hero: str | None
) -> Page:
    hero_block = (
        f'<video class="hero-media" src="{hero}" autoplay loop muted playsinline '
        f'preload="metadata"></video>'
        if hero
        else '<div class="hero-media placeholder">run <code>make site</code> with renders in '
        "<code>outputs/</code> to see this</div>"
    )
    chain = '<span class="arrow">→</span>'.join(
        f'<span class="chip">{part}</span>'
        for part in (
            "temperature field",
            "surface radiance",
            "atmospheric path",
            "optics",
            "detector",
            "noise",
            "ISP",
            "pixels",
        )
    )
    tiles = [
        (
            "per-point temperature",
            "Every cell of a surface holds its own energy balance. One "
            "temperature per object is not a coarser thermal scene — it is a different one.",
        ),
        (
            "bands are data",
            "LWIR, MWIR, SWIR and NIR come out of the same kernel. Adding a camera "
            "is a YAML file, not an edit to the radiance path.",
        ),
        (
            "an engine-free core",
            "<code>src/irsim/</code> imports no engine module, so the physics "
            "is testable in seconds on a laptop with no GPU. A test fails the build if that stops "
            "being true.",
        ),
        (
            "approximations on the record",
            f"{stats['adrs']} decision records say which fidelity was "
            "taken on purpose, and what it would cost to raise it.",
        ),
    ]
    numbers = [
        (f"{stats['modules']:,}", "modules in <code>src/</code>"),
        (f"{stats['tests']:,}", "test functions, none needing a GPU"),
        (f"{stats['adrs']:,}", "decision records"),
        (f"{stats['configs']:,}", "configuration files"),
        (f"{stats['spec_sections']:,}", "specification sections cited by the code"),
        (f"{stats['steps_done']}/{stats['steps_total']}", "roadmap steps shipped"),
    ]
    body = [
        '<div class="hero">',
        '<div class="hero-text">',
        "<p>irsim renders what a real LWIR, MWIR, SWIR or NIR camera would see, with radiometry "
        "that closes in physical units — so the frames are usable for sensor trade studies, "
        "perception development and sim-to-real work, not only for looking thermal.</p>",
        '<p class="hero-links">'
        '<a class="button" href="gallery/">See what it produces</a>'
        '<a class="button ghost" href="physics/">Read the physics</a>'
        f'<a class="button ghost" href="{GITHUB}" target="_blank" rel="noopener">Source</a></p>',
        "</div>",
        hero_block,
        "</div>",
        f'<div class="chain">{chain}</div>',
        '<p class="chain-note">The signal order of <a href="physics/">the specification</a>. Every '
        "link is a recognised physical model whose units close; every approximation is a written "
        "decision rather than an accident.</p>",
        '<h2 id="what-is-different">What this one does differently</h2>',
        '<div class="tiles">',
        *[f"<div class='tile'><h3>{t}</h3><p>{d}</p></div>" for t, d in tiles],
        "</div>",
        '<h2 id="by-the-numbers">The repository, counted at build time</h2>',
        '<div class="numbers">',
        *[
            f"<div class='number'><b>{value}</b><span>{label}</span></div>"
            for value, label in numbers
        ],
        "</div>",
    ]
    if plan is not None:
        body.append('<h2 id="where-it-is">Where the plan is</h2>')
        body.append(
            "<p>Phases run repair → point-wise physics → aerial → maritime → ground → "
            "cross-cutting; the order is the owner's, recorded in ADR 0003.</p>"
        )
        body.append('<div class="bars">')
        for phase, done, total in plan.by_phase:
            pct = round(100 * done / total) if total else 0
            body.append(
                f'<div class="bar"><span class="bar-label">phase {html.escape(phase)}</span>'
                '<span class="bar-track">'
                f'<span class="bar-fill" style="width:{pct}%"></span></span>'
                f'<span class="bar-value">{done}/{total}</span></div>'
            )
        body.append("</div>")
        queue = "".join(
            f"<li><code>{html.escape(sid)}</code> <span class='lane'>{html.escape(lane)}</span> "
            f"{site_markdown.render(what[:240]).html[3:-4]}</li>"
            for sid, lane, what in plan.queue[:5]
        )
        body.append(f'<h3 id="do-next">Next, in order</h3><ol class="queue">{queue}</ol>')
        body.append('<p><a href="roadmap/">The whole plan →</a></p>')
    body.append('<h2 id="read-next">Read next</h2>')
    body.append('<div class="cards">')
    for url, title, note in [
        ("gallery/", "What it produces", "Frames and clips, with what each one demonstrates."),
        ("physics/", "Physics model", "The specification the code cites section by section."),
        (
            "status/",
            "Status",
            "Subsystem by subsystem: what is implemented and what it is verified against.",
        ),
        (
            "validation/",
            "Validation",
            "Measured against public imagery — including where it fails.",
        ),
        ("decisions/", "Decision log", "Why each approximation was chosen."),
        ("code/", "Code map", "Every module in the tree, measured at build time."),
    ]:
        body.append(f'<a class="card" href="{url}"><h3>{title}</h3><p>{note}</p></a>')
    body.append("</div>")
    return Page(
        url="",
        title="irsim",
        subtitle="A physically-based multi-band infrared camera simulator for NVIDIA Isaac Sim.",
        body="\n".join(body),
        nav_section="Start",
        wide=True,
    )


# ---------------------------------------------------------------------------------------------
# assembly


def build(out: pathlib.Path, outputs: pathlib.Path, *, media: bool = True) -> dict[str, int]:
    repo = REPO
    out.mkdir(parents=True, exist_ok=True)

    adr_paths = sorted((repo / "docs" / "decisions").glob("*.md"))
    url_map: dict[str, str] = {source: url for source, url, *_ in DOCUMENTS}
    for path in adr_paths:
        url_map[f"docs/decisions/{path.name}"] = f"decisions/{path.stem}/"
    collection_pages: dict[str, list[pathlib.Path]] = {}
    for directory, url, *_ in COLLECTIONS:
        if directory == "docs/decisions":
            collection_pages[directory] = adr_paths
            continue
        paths = sorted((repo / directory).glob("*.md"))
        collection_pages[directory] = paths
        for path in paths:
            url_map[f"{directory}/{path.name}"] = f"{url}{path.stem}/"
    resolver = Resolver(url_map, repo)

    pages: list[Page] = []
    for source, url, title, group, subtitle in DOCUMENTS:
        pages.append(document_page(repo, source, url, title, group, subtitle, resolver))

    adrs: list[site_survey.Adr] = []
    for directory, url, title, group, blurb in COLLECTIONS:
        made: list[Page] = []
        for path in collection_pages[directory]:
            source = f"{directory}/{path.name}"
            page_url = url_map[source]
            page = document_page(repo, source, page_url, path.stem, group, "", resolver)
            if page.headings and page.headings[0].level == 1:
                page.title = page.headings[0].text
            else:
                doc_title = site_markdown.render(
                    (repo / source).read_text(encoding="utf-8").split("\n")[0].lstrip("# ")
                )
                page.title = _plain(doc_title.html) or path.stem
            if directory == "docs/decisions":
                adrs.append(site_survey.adr_meta(path, page_url))
            made.append(page)
        pages.extend(made)
        if directory == "docs/decisions":
            pages.append(decision_index(adrs, url, group, blurb))
        else:
            pages.append(collection_index(made, url, title, group, blurb))

    gallery = site_gallery.GalleryBuilder(
        repo / "site" / "gallery.yaml",
        outputs,
        out / "media",
        media_prefix="../media/",
        encode=media,
    ).build("gallery/")
    pages.append(gallery.page)

    pages.append(site_survey.code_map(repo))
    pages.append(site_survey.config_catalogue(repo))

    plan = site_survey.plan(repo)
    stats = {
        "modules": len(site_survey.modules(repo)),
        "tests": sum(t for _, t, _ in site_survey.test_counts(repo).values()),
        "adrs": len(adrs),
        "configs": len(list((repo / "configs").rglob("*.yaml"))),
        "spec_sections": len({s for m in site_survey.modules(repo) for s in m.sections}),
        "steps_done": plan.done if plan else 0,
        "steps_total": plan.total if plan else 0,
    }
    hero = None
    hero_asset = next(
        (a for a in gallery.assets if a.url.endswith("quad_pointwise_vs_objectwise.mp4")), None
    )
    if hero_asset:
        hero = f"media/{hero_asset.url}"
    pages.insert(0, home_page(repo, stats, plan, hero))

    groups = nav_groups(pages)
    built = dt.datetime.now(dt.UTC).strftime("%Y-%m-%d %H:%M UTC")
    commit = site_survey.commit()
    for page in pages:
        target = out / page.out_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(render_page(page, groups, built=built, commit=commit), encoding="utf-8")

    write_search(out, pages)
    copy_assets(repo, out)
    (out / ".nojekyll").write_text("", encoding="utf-8")

    total = sum(f.stat().st_size for f in out.rglob("*") if f.is_file())
    return {
        "unresolved": sorted(resolver.unresolved),
        # The headline figures, returned so a caller (and the test) can check what was published
        # against what was counted, in one run: this tree is edited by several sessions at once,
        # so recounting afterwards races against them.
        "stats": stats,
        "pages": len(pages),
        "media": len(gallery.assets),
        "missing": len(gallery.missing),
        "bytes": total,
        "media_bytes": sum(a.bytes for a in gallery.assets),
        "source_bytes": sum(a.source_bytes for a in gallery.assets),
    }


def nav_groups(pages: list[Page]) -> list[NavGroup]:
    """The sidebar: one group per section, collections collapsed to their index."""
    wanted = {
        "Start": ["", "gallery/", "status/"],
        "Demos": [],
        "Physics": ["physics/", "spec-issues/"],
        "Plan": ["roadmap/", "decisions/", "changelog/"],
        "Evidence": ["validation/", "research/"],
        "Reference": ["code/", "configs/", "guide/"],
    }
    titles = {page.url: page.title for page in pages}
    #: Sidebar labels, where a page's own title is longer than a nav entry should be.
    titles.update({"gallery/": "Demo gallery", "": "Overview"})
    groups: list[NavGroup] = []
    for name in NAV_ORDER:
        urls = wanted.get(name, [])
        items = [NavItem(titles.get(url, url), url) for url in urls if url in titles]
        if name == "Start":
            items = [NavItem("Overview", ""), *[i for i in items if i.url]]
        if items:
            groups.append(NavGroup(name, items))
    return groups


def write_search(out: pathlib.Path, pages: list[Page]) -> None:
    """A flat index of pages and their headings.

    Small enough to ship whole and search inside the page, which is why the site needs no search
    service and works from `file://`.
    """
    index = []
    for page in pages:
        index.append(
            {
                "t": page.title,
                "u": page.url,
                "s": page.nav_section,
                "h": [{"t": h.text, "a": h.slug} for h in page.headings if h.level <= 3][:60],
                "x": (page.search_text or _plain(page.body))[:400],
            }
        )
    (out / "search.json").write_text(json.dumps(index, separators=(",", ":")), encoding="utf-8")


def copy_assets(repo: pathlib.Path, out: pathlib.Path) -> None:
    target = out / "assets"
    target.mkdir(parents=True, exist_ok=True)
    for path in sorted((repo / "site" / "assets").glob("*")):
        if path.is_file():
            shutil.copy2(path, target / path.name)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--out", type=pathlib.Path, default=REPO / "_site")
    parser.add_argument(
        "--outputs",
        type=pathlib.Path,
        default=pathlib.Path(os.environ.get("IRSIM_OUTPUTS", REPO / "outputs")),
        help="the render tree the gallery draws on (default: outputs/, or $IRSIM_OUTPUTS)",
    )
    parser.add_argument("--no-media", action="store_true", help="skip the gallery encode")
    parser.add_argument("--serve", action="store_true", help="serve the result on localhost")
    parser.add_argument("--port", type=int, default=8000)
    args = parser.parse_args()

    result = build(args.out, args.outputs, media=not args.no_media)
    print(
        f"{result['pages']} pages, {result['media']} media files "
        f"({result['media_bytes'] / 1e6:.1f} MB re-encoded from "
        f"{result['source_bytes'] / 1e6:.1f} MB), {result['bytes'] / 1e6:.1f} MB total → {args.out}"
    )
    for source, href in result["unresolved"]:
        print(f"  dead link in {source}: {href}", file=sys.stderr)
    if result["missing"]:
        print(
            f"  {result['missing']} manifest entries were not in {args.outputs} "
            "(listed on the page)"
        )
    print(
        "  preview it with --serve: the in-page search fetches search.json, which a browser "
        "refuses over file://"
    )
    if result["bytes"] > 900e6:
        print("  WARNING: over 900 MB; GitHub Pages publishes about 1 GB", file=sys.stderr)

    if args.serve:
        import functools
        import http.server

        handler = functools.partial(http.server.SimpleHTTPRequestHandler, directory=str(args.out))
        print(f"serving {args.out} on http://localhost:{args.port}/ — ctrl-c to stop")
        http.server.ThreadingHTTPServer(("127.0.0.1", args.port), handler).serve_forever()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
