#!/usr/bin/env python3
"""Regenerate the committed synthetic weather sample (M6.2, ADR 0032).

    python scripts/generate_weather.py [--out data/weather/clear_midlat_summer_48h.csv]

The arguments below ARE the definition of the file; tests/unit/test_weather_io.py regenerates it
with the same call and requires a bit-exact match, so change them here and re-run.
"""

from __future__ import annotations

import argparse
import pathlib
import sys
from datetime import datetime, timezone

REPO = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_OUT = REPO / "data" / "weather" / "clear_midlat_summer_48h.csv"

SAMPLE_ARGS: dict[str, float] = {
    "hours": 48.0,
    "utc_offset_h": 2.0,  # central European summer time: a mid-latitude June day
    "t_mean_k": 295.15,
    "t_swing_k": 12.0,
    "t_max_hour_local": 15.0,
    "dewpoint_k": 285.15,
    "wind_speed_m_s": 2.5,
    "cloud_fraction": 0.05,
    "dni_peak_w_m2": 850.0,
    "dhi_peak_w_m2": 110.0,
    "sunrise_hour_local": 5.5,
    "sunset_hour_local": 21.0,
    "visibility_m": 23000.0,
    "step_s": 3600.0,
}
SAMPLE_START = datetime(2024, 6, 21, 0, 0, tzinfo=timezone.utc)
SAMPLE_COMMENT = (
    "SYNTHETIC clear mid-latitude summer day, 48 h from 2024-06-21T00:00Z, local = UTC+2.\n"
    "Generated by scripts/generate_weather.py (irsim.thermal.weather_io.synthetic_clear_day):\n"
    "sinusoidal T_air 295.15 +- 6 K (max 15:00 local), RH from a 12 C dew point, half-sine\n"
    "DNI 850 / DHI 110 W m^-2 peak between 05:30 and 21:00 local, wind 2.5 m/s, cloud 0.05,\n"
    "visibility 23 km. Not a measurement; a documented fixture (ADR 0032)."
)


# A coastal day for the maritime scenes (MM.6). Same generator, different water: a sea breeze
# that is calm at dawn and blows 9 m/s by mid-afternoon, over a sea whose temperature barely moves.
# The wind is the point -- it sets the Cox-Munk slope statistics the infrared sea reads AND the
# wave amplitude the visible surface is built from, so a maritime scene run on the constant
# 2.5 m/s inland fixture is a glassy sea all day, which is neither interesting nor typical.
COASTAL_ARGS: dict[str, float] = {
    "hours": 48.0,
    "utc_offset_h": 1.0,  # western Mediterranean
    "t_mean_k": 295.65,
    "t_swing_k": 6.0,  # maritime: the sea damps the diurnal swing to half the inland one
    "t_max_hour_local": 15.0,
    "dewpoint_k": 289.15,  # humid marine air, RH ~ 0.7
    "wind_speed_m_s": 5.5,
    "wind_swing_m_s": 7.0,  # 2.0 m/s at dawn to 9.0 m/s mid-afternoon
    "wind_max_hour_local": 16.0,
    "cloud_fraction": 0.10,
    "dni_peak_w_m2": 880.0,
    "dhi_peak_w_m2": 130.0,
    "sunrise_hour_local": 6.0,
    "sunset_hour_local": 20.5,
    "visibility_m": 30000.0,
    "step_s": 3600.0,
}
COASTAL_OUT = REPO / "data" / "weather" / "coastal_sea_breeze_48h.csv"
COASTAL_START = datetime(2024, 6, 21, 0, 0, tzinfo=timezone.utc)
COASTAL_COMMENT = (
    "SYNTHETIC coastal summer day with a sea breeze, 48 h from 2024-06-21T00:00Z, local = UTC+1.\n"
    "Generated by scripts/generate_weather.py (irsim.thermal.weather_io.synthetic_clear_day):\n"
    "sinusoidal T_air 295.65 +- 3 K (maritime damping, max 15:00 local), RH from a 16 C dew\n"
    "point, half-sine DNI 880 / DHI 130 W m^-2 between 06:00 and 20:30 local, WIND 2.0-9.0 m/s\n"
    "peaking at 16:00 local, cloud 0.10, visibility 30 km. "
    "Not a measurement; a documented fixture (ADR 0032)."
)


# An overcast night for the vehicle scenes (MP.4). The point of it is what it REMOVES. Under thick
# cloud the sky radiates at close to air temperature, so §5.3's downwelling longwave nearly matches
# what a surface emits and every surface settles within a kelvin or two of ambient regardless of its
# material, its tilt or what it did yesterday. That is the only condition under which a car and the
# asphalt it stands on look the same in LWIR -- which is the first frame the ignition demo needs.
#
# Under a CLEAR night the same scene is not flat at all: the sky is 40-50 K below ambient, every
# upward-facing surface radiates to it and cools, and a car standing over asphalt blocks that cold
# sky and leaves a warm car-shaped patch on the ground (ADR 0088) before its engine has ever run.
# That is the real and well-known phenomenon; it is simply not what a demo of *engine* heat wants
# in frame 0.
#
# No direct beam at all, and the diurnal swing is damped to a third of the clear-sky fixture's,
# which is what thick cloud does to it.
OVERCAST_ARGS: dict[str, float] = {
    "hours": 48.0,
    "utc_offset_h": 2.0,
    "t_mean_k": 288.15,
    "t_swing_k": 4.0,  # overcast damps the clear-sky 12 K to a third
    "t_max_hour_local": 15.0,
    "dewpoint_k": 284.15,  # RH ~ 0.88 at the night minimum: cloudy, not fogged in
    "wind_speed_m_s": 1.5,  # light: a still night, so free convection is not swamped
    "cloud_fraction": 0.98,
    "dni_peak_w_m2": 0.0,  # thick overcast: no direct beam reaches the ground
    "dhi_peak_w_m2": 150.0,
    "sunrise_hour_local": 5.5,
    "sunset_hour_local": 21.0,
    "visibility_m": 8000.0,
    "step_s": 3600.0,
}
OVERCAST_OUT = REPO / "data" / "weather" / "overcast_still_48h.csv"
OVERCAST_START = datetime(2024, 6, 21, 0, 0, tzinfo=timezone.utc)
OVERCAST_COMMENT = (
    "SYNTHETIC thick-overcast still day, 48 h from 2024-06-21T00:00Z, local = UTC+2.\n"
    "Generated by scripts/generate_weather.py (irsim.thermal.weather_io.synthetic_clear_day):\n"
    "sinusoidal T_air 288.15 +- 2 K (cloud damps the clear-sky swing to a third, max 15:00\n"
    "local), RH 0.78-0.88 from an 11 C dew point, NO direct beam and half-sine DHI 150 W m^-2\n"
    "between 05:30 and 21:00 local, wind 1.5 m/s, cloud 0.98, visibility 8 km. The condition\n"
    "under which every surface sits within a kelvin or two of ambient, which is what the MP.4\n"
    "ignition demo needs in frame 0. Not a measurement; a documented fixture (ADR 0032)."
)


# A fair-weather cumulus day, for the scenes whose subject is a target against SKY. The clear
# fixture carries cloud 0.05, which is a sky with nothing in it: `generate_sky_cloud` lays its
# coverage over the whole hemisphere, so at 0.05 a 31 x 25 degree field almost never contains a
# cloud and the "cloud in both bands" claim is untestable on it.
#
# 0.45 is **SCT** in the meteorological sense -- 3-4 oktas, the fair-weather cumulus of a summer
# afternoon -- and it is the interesting condition rather than the extreme one. Overcast (0.98)
# would be easier and would prove nothing: a fully covered sky is a blackbody at air temperature,
# so it has no structure for a detector to false-alarm on and the sun is gone. Broken cloud is
# where a sky-background target is actually hard, because cloud edges are the clutter.
#
# The sun still shines: this is a day of clouds WITH gaps, so the direct beam is only modestly
# reduced and the diffuse component rises, which is what a real broken sky does. Keeping DNI high
# is what lets the aircraft's sunlit skin still separate from its shaded side.
CUMULUS_ARGS: dict[str, float] = {
    "hours": 48.0,
    "utc_offset_h": 2.0,
    "t_mean_k": 294.15,
    "t_swing_k": 9.0,  # broken cloud damps the clear-sky 12 K, but nothing like overcast's third
    "t_max_hour_local": 15.0,
    "dewpoint_k": 286.15,  # RH ~ 0.6 at the afternoon peak: the humidity cumulus needs
    "wind_speed_m_s": 3.5,  # the convective breeze that builds the cumulus in the first place
    "cloud_fraction": 0.45,
    "dni_peak_w_m2": 800.0,
    "dhi_peak_w_m2": 180.0,  # more diffuse than the clear day: cloud sides scatter into the gaps
    "sunrise_hour_local": 5.5,
    "sunset_hour_local": 21.0,
    "visibility_m": 25000.0,
    "step_s": 3600.0,
}
CUMULUS_OUT = REPO / "data" / "weather" / "scattered_cumulus_48h.csv"
CUMULUS_START = datetime(2024, 6, 21, 0, 0, tzinfo=timezone.utc)
CUMULUS_COMMENT = (
    "SYNTHETIC fair-weather cumulus day, 48 h from 2024-06-21T00:00Z, local = UTC+2.\n"
    "Generated by scripts/generate_weather.py (irsim.thermal.weather_io.synthetic_clear_day):\n"
    "sinusoidal T_air 294.15 +- 4.5 K (max 15:00 local), RH from a 13 C dew point, half-sine\n"
    "DNI 800 / DHI 180 W m^-2 between 05:30 and 21:00 local, wind 3.5 m/s, cloud 0.45 (SCT,\n"
    "3-4 oktas), visibility 25 km. The sky-target condition: cloud WITH gaps, so the direct\n"
    "beam survives and cloud edges are clutter. Not a measurement; a documented fixture "
    "(ADR 0032)."
)


def build():  # type: ignore[no-untyped-def]
    from irsim.thermal.weather_io import synthetic_clear_day

    return synthetic_clear_day(SAMPLE_START, **SAMPLE_ARGS)


def build_coastal():  # type: ignore[no-untyped-def]
    from irsim.thermal.weather_io import synthetic_clear_day

    return synthetic_clear_day(COASTAL_START, **COASTAL_ARGS)


def build_overcast():  # type: ignore[no-untyped-def]
    from irsim.thermal.weather_io import synthetic_clear_day

    return synthetic_clear_day(OVERCAST_START, **OVERCAST_ARGS)


def build_cumulus():  # type: ignore[no-untyped-def]
    from irsim.thermal.weather_io import synthetic_clear_day

    return synthetic_clear_day(CUMULUS_START, **CUMULUS_ARGS)


def main() -> int:
    from irsim.thermal.weather_io import write_weather_csv

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=pathlib.Path, default=None)
    ap.add_argument(
        "--which",
        choices=("inland", "coastal", "overcast", "cumulus", "all"),
        default="all",
        help="inland is the original M6.2 fixture; coastal is the sea-breeze day the maritime "
        "scenes need (MM.6); overcast is the flat still night the MP.4 vehicle demo needs; "
        "cumulus is the broken sky a sky-background target is actually hard against",
    )
    args = ap.parse_args()

    jobs = []
    if args.which in ("inland", "all"):
        jobs.append((build(), args.out or DEFAULT_OUT, SAMPLE_COMMENT))
    if args.which in ("coastal", "all"):
        jobs.append((build_coastal(), args.out or COASTAL_OUT, COASTAL_COMMENT))
    if args.which in ("overcast", "all"):
        jobs.append((build_overcast(), args.out or OVERCAST_OUT, OVERCAST_COMMENT))
    if args.which in ("cumulus", "all"):
        jobs.append((build_cumulus(), args.out or CUMULUS_OUT, CUMULUS_COMMENT))
    if args.out is not None and len(jobs) > 1:
        ap.error("--out names one file, so pass a single --which with it")

    for series, out, comment in jobs:
        out.parent.mkdir(parents=True, exist_ok=True)
        write_weather_csv(series, out, comment=comment)
        print(f"wrote {out} ({series.n} rows, hash {series.content_hash[:12]})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
